### ISSUE TITLE
Check whether long running thread code is finished or not, using `channel`.

### ISSUE THREAD

**Issue by spikeekips** [liamzdenek/go-pthreads#1]
(This is not bug report or enhancement :)

I tested for long running routine and found there is no way to check the thread is alive or not. Of course `Thread.Running` is available but it seems to be incomplete. This is simple method to check whether long running routine is finished or not, using `channel`.

``` Go
_ch := make(chan bool)

thread := pthread.Create(func() {
    ... long running routine ...

    _ch <- true
})

<- _ch
```

Thanks.

**Comment by liamzdenek** [comment]
closed as not an issue
